# Minimum and Maximum Values in a Random Array

---

### Problem Statement

<code>Write a NumPy program to create a 5×5 array with random values and find the minimum and maximum values.</code>

---


In [1]:
import numpy as np

arr = np.random.random((5, 5))

print("Original Array:")
print(arr)
print("Minimum and Maximum Values:")
print(arr.min(), arr.max())


Original Array:
[[0.93923868 0.20959855 0.26949071 0.36386445 0.21041655]
 [0.52307528 0.81227386 0.32081726 0.57471705 0.21255687]
 [0.17514646 0.58013283 0.60520239 0.81473016 0.11222016]
 [0.58930437 0.45963931 0.34296174 0.31645153 0.01135968]
 [0.78423549 0.88009517 0.26291299 0.67242753 0.26756782]]
Minimum and Maximum Values:
0.011359679223831742 0.9392386766784464
