# Row-wise Normalization of a Random Matrix

---

### Problem Statement

<code>
Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.
</code>

---


In [1]:
import numpy as np

arr = np.random.random((5, 5))

row_sums = arr.sum(axis=1, keepdims=True)
normalized = arr / row_sums

print("Original Array:")
print(arr)
print("Row-wise Normalized Array:")
print(normalized)


Original Array:
[[0.33680169 0.48504582 0.22765246 0.89380177 0.82085652]
 [0.13349612 0.6984528  0.89596667 0.49989024 0.744605  ]
 [0.53317755 0.12473146 0.61983898 0.13067857 0.47551375]
 [0.68676393 0.01877826 0.67236274 0.32587091 0.99731446]
 [0.70027145 0.98906242 0.7245646  0.27933023 0.04816745]]
Row-wise Normalized Array:
[[0.12184602 0.17547686 0.08235869 0.32335405 0.29696437]
 [0.04491173 0.23497855 0.3014276  0.1681767  0.25050541]
 [0.28301191 0.06620776 0.32901201 0.0693645  0.25240383]
 [0.25425434 0.0069521  0.24892272 0.12064421 0.36922663]
 [0.25544336 0.36078785 0.26430496 0.10189342 0.01757041]]
