# Converting Nested List to 2D NumPy Array

---

### Problem Statement

<code>
Write a NumPy program to convert a nested Python list to a 2D NumPy array and print the array.
</code>

---


In [1]:
import numpy as np

nested_list = [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]]

arr = np.array(nested_list)

print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
