In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.12550041, 0.09051921, 0.10179424, 0.61177919, 0.92841856])

In [16]:
np.random.rand(5,5)

array([[2.50930175e-01, 1.41503878e-04, 2.00261022e-02, 1.72585949e-01,
        9.16824504e-01],
       [9.84577868e-01, 3.63827978e-01, 1.34449834e-01, 8.37869813e-01,
        2.78698453e-01],
       [4.28756437e-01, 2.35661149e-01, 4.09116647e-01, 1.19462817e-01,
        6.37219334e-02],
       [9.88653892e-01, 4.83424346e-01, 1.84485374e-01, 2.65475551e-01,
        4.93171567e-01],
       [1.38496177e-01, 4.92925319e-01, 7.44458871e-01, 6.51380628e-01,
        2.24484153e-01]])

In [17]:
np.random.randn(2)

array([-1.32251426, -0.45644258])

In [18]:
np.random.randint(1,100,10)

array([29, 93, 30, 22, 45, 61, 52, 86, 53, 59], dtype=int32)

In [19]:
arr = np.arange(25)

In [20]:
ranarr = np.random.randint(1,50,10)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr

array([22, 34, 44, 15, 27, 20, 30, 13, 35, 15], dtype=int32)

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
# max ValueError
ranarr.max()

np.int32(44)

In [25]:
ranarr.min()

np.int32(13)

In [26]:
# index 
ranarr.argmax()

np.int64(2)

In [27]:
ranarr.argmin()

np.int64(7)

In [29]:
#shape
arr.shape

(25,)

In [30]:
arr =arr.reshape(5,5)

In [31]:
arr.shape

(5, 5)

In [32]:
#data type
arr.dtype

dtype('int64')

In [33]:
from numpy.random import randint

### numpy indexing and selection

In [34]:
arr = np.arange(0,11)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

np.int64(8)

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [39]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[0:5]=100

In [41]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [42]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
slice_of_arr = arr[0:6]

In [44]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [45]:
slice_of_arr[:]=99

In [46]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [47]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [48]:
arr_copy = arr.copy()

In [49]:
arr_copy[:]=100

In [50]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [51]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
#indexing 2d array

In [54]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [55]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d[0][0]

np.int64(5)

In [57]:
arr_2d[0,0]

np.int64(5)

In [58]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
#conditional selection
arr = np.arange(1,11)

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
bool_arr=arr >5 

In [63]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

### numpy operations

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [69]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [71]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
arr*10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [73]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [74]:
1/0

ZeroDivisionError: division by zero

In [75]:
arr/arr

C:\Users\JayKalsariya\AppData\Local\Temp\ipykernel_17216\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [76]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [77]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [78]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [79]:
arr.max()

np.int64(10)

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [82]:
np.log(arr)

C:\Users\JayKalsariya\AppData\Local\Temp\ipykernel_17216\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])