# Broadcasting-Compatible Reshaping

---

### Problem Statement

<code>
Given two arrays, x = np.array([1, 2, 3]) and y = np.array([4, 5, 6, 7, 8, 9]).
Write a NumPy program that reshapes x and y to make them broadcast-compatible and perform element-wise multiplication.
</code>

---


In [1]:
import numpy as np

x = np.array([1, 2, 3]).reshape(3, 1)
y = np.array([4, 5, 6, 7, 8, 9]).reshape(1, 6)

result = x * y

print(result)


[[ 4  5  6  7  8  9]
 [ 8 10 12 14 16 18]
 [12 15 18 21 24 27]]
