# 8×8 Checkerboard Pattern

---

### Problem Statement

<code>Write a NumPy program to create an 8×8 matrix and fill it with a checkerboard pattern.</code>

---

### Expected Pattern



In [1]:
import numpy as np

board = np.zeros((8, 8), dtype=int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1

print(board)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
