# Tuple-Based Advanced Indexing in NumPy

---

### Problem Statement

<code>
Write a NumPy program that creates a 2D NumPy array and uses a tuple of arrays to index and select a specific set of elements.
</code>

---


In [1]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])

selected = arr[(row_indices, col_indices)]

print("Original Array:")
print(arr)
print("Selected Elements:")
print(selected)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Selected Elements:
[3 5 7]
